"use client";

interface TermsModalProps {
  isOpen: boolean;
  onAccept: () => void;
  onDecline?: () => void;
}

export default function TermsModal({ isOpen, onAccept, onDecline }: TermsModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 z-[100] flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-200">
          <h2 className="text-2xl font-bold text-gray-800">Terms of Use & Privacy Policy</h2>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-4">
          <div className="prose prose-sm max-w-none text-gray-700 space-y-4">
            <section>
              <h3 className="text-lg font-semibold text-gray-800 mb-2">Research Study Notice</h3>
              <p>
                This platform is operated for research purposes. By using this service, you acknowledge
                and consent to the collection and analysis of your usage data and interaction events.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-semibold text-gray-800 mb-2">Data Collection</h3>
              <p>We collect the following information:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>User queries and interactions with the AI assistant</li>
                <li>Session information and timestamps</li>
                <li>Click events and browsing behavior</li>
                <li>Selected model preferences and settings</li>
              </ul>
              <p className="mt-2">
                This data is used solely for research purposes to improve AI-powered brand exploration
                and understand user interaction patterns.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-semibold text-gray-800 mb-2">Prohibited Uses</h3>
              <p>Our Services must NOT be used for:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Any illegal, harmful, or violent purposes</li>
                <li>Racist, discriminatory, or hateful content</li>
                <li>Sexual or other offensive purposes</li>
                <li>Uploading sensitive personal information (SSN, credit cards, passwords, etc.)</li>
                <li>Harassment, abuse, or threatening behavior</li>
              </ul>
            </section>

            <section>
              <h3 className="text-lg font-semibold text-gray-800 mb-2">AI Limitations & Disclaimer</h3>
              <p>
                Due to the nature of artificial intelligence (AI) technologies, the Services may make
                mistakes and provide responses that are inaccurate, incomplete, or inappropriate for
                your input.
              </p>
              <p className="mt-2 font-medium">
                We are not responsible for any such mistakes, inaccuracies, or inappropriate responses.
                You should independently verify the accuracy of all responses before relying on them.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-semibold text-gray-800 mb-2">No Warranty</h3>
              <p>
                The service is provided "as is" without warranties of any kind. We do not guarantee
                the accuracy, completeness, or reliability of any content generated by the AI.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-semibold text-gray-800 mb-2">Data Retention</h3>
              <p>
                Your chat history is stored locally in your browser. Session data and events are
                transmitted to our research database for analysis. You may clear your local chat
                history at any time using the sidebar options.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-semibold text-gray-800 mb-2">Your Consent</h3>
              <p>
                By clicking "Agree and Continue" below, you:
              </p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Agree to be bound by these Terms of Use</li>
                <li>Acknowledge receipt and understanding of our Privacy Policy</li>
                <li>Consent to the collection and use of your data as described above</li>
                <li>Confirm you will not use the service for prohibited purposes</li>
                <li>Understand the limitations and disclaimers regarding AI accuracy</li>
              </ul>
            </section>

            <section className="text-sm text-gray-600 mt-6 pt-4 border-t border-gray-200">
              <p>
                <strong>Questions?</strong> If you have questions about these terms or our data
                collection practices, please contact the research team.
              </p>
              <p className="mt-2">
                <strong>Last Updated:</strong> {new Date().toLocaleDateString()}
              </p>
            </section>
          </div>
        </div>

        {/* Footer - Action Buttons */}
        <div className="px-6 py-4 border-t border-gray-200 flex gap-3">
          {onDecline && (
            <button
              onClick={onDecline}
              className="flex-1 px-6 py-3 bg-gray-200 hover:bg-gray-300 text-gray-700 font-medium rounded-lg transition-colors"
            >
              Decline
            </button>
          )}
          <button
            onClick={onAccept}
            className="flex-1 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg transition-colors"
          >
            Agree and Continue
          </button>
        </div>
      </div>
    </div>
  );
}
