version: '3.8'

services:
  # Backend API Service (Development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: llm-backend-dev
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGO_DB=${MONGO_DB:-llm_experiment}
      - LITELLM_MODEL=${LITELLM_MODEL:-gpt-4o-mini}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/app  # Mount source code for hot reload
    restart: unless-stopped
    networks:
      - llm-network

  # Local MongoDB (for development)
  mongodb:
    image: mongo:7.0
    container_name: llm-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=llm_experiment
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - llm-network

  # Mongo Express (MongoDB Web UI)
  mongo-express:
    image: mongo-express:latest
    container_name: llm-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge

volumes:
  mongodb_data:
